### ISSUE TITLE
NetSerializer metadata is wrong

### ISSUE THREAD

**Issue by tomba** [aumcode/serbench#27]
NetSerializer uses custom binary format, not textual JSON as defined in the current SerializerInfo.

**Comment by itadapter** [comment]
correct it. and include the whole attr text here or send pull req

**Comment by leo-gan** [comment]
I will do this.

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/

On Tue, Aug 4, 2015 at 10:10 AM, Dmitriy@ITAdapter <notifications@github.com

**Comment by leo-gan** [comment]
Fixed. 
Tomi, thank you for mention that!

**Comment by tomba** [comment]
Thanks @leo-gan, but you missed the line with:

FormatName = "JSON"

Sorry I wasn't clear on the wrong lines in my original report.

**Comment by leo-gan** [comment]
Done :)

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/
